#ifndef RCC_CONFIG_H
#define RCC_CONFIG_H

											/* Configure RCC_AHB_ENR Options : 1- ENABLE	2- DISABLE   */

#define 		RCC_AHB_10_SDIO				DISABLE
#define 		RCC_AHB_08_FSMC				DISABLE
#define 		RCC_AHB_06_CRC				DISABLE
#define 		RCC_AHB_04_FLITF			DISABLE
#define 		RCC_AHB_02_SRAM				DISABLE
#define 		RCC_AHB_01_DMA2 			DISABLE
#define 		RCC_AHB_00_DMA1 			ENABLE

											/* Configure RCC_APB2_ENR Options : 1- ENABLE	2- DISABLE   */

#define 		RCC_APB2_21_TIM11 			DISABLE
#define 		RCC_APB2_20_TIM10 			DISABLE
#define 		RCC_APB2_19_TIM9 			DISABLE
#define 		RCC_APB2_15_ADC3			DISABLE
#define 		RCC_APB2_14_USART1			DISABLE
#define 		RCC_APB2_13_TIM8			DISABLE
#define 		RCC_APB2_12_SPI1			DISABLE
#define 		RCC_APB2_11_TIM1			DISABLE
#define 		RCC_APB2_10_ADC2			DISABLE
#define 		RCC_APB2_09_ADC1			DISABLE
#define 		RCC_APB2_08_IOPG			DISABLE
#define 		RCC_APB2_07_IOPF			DISABLE
#define 		RCC_APB2_06_IOPE			DISABLE
#define 		RCC_APB2_05_IOPD			DISABLE
#define 		RCC_APB2_04_IOPC			DISABLE
#define 		RCC_APB2_03_IOPB			DISABLE
#define 		RCC_APB2_02_IOPA			DISABLE
#define 		RCC_APB2_00_AFIO 			DISABLE

												/* Configure RCC_APB1_ENR Options : 1- ENABLE	2- DISABLE   */

#define 		RCC_APB1_29_DAC 			DISABLE
#define 		RCC_APB1_28_PWR				DISABLE
#define 		RCC_APB1_27_BKP				DISABLE
#define 		RCC_APB1_25_CAN				DISABLE
#define 		RCC_APB1_23_USB				DISABLE
#define 		RCC_APB1_22_I2C2			DISABLE
#define 		RCC_APB1_21_I2C1 			DISABLE
#define 		RCC_APB1_20_UART5 			DISABLE
#define 		RCC_APB1_19_UART4 			DISABLE
#define 		RCC_APB1_18_USART3 			DISABLE
#define 		RCC_APB1_17_USART2 			DISABLE
#define 		RCC_APB1_15_SPI3			DISABLE
#define 		RCC_APB1_14_SPI2			DISABLE
#define 		RCC_APB1_11_WWDG			DISABLE
#define 		RCC_APB1_08_TIM14			DISABLE
#define 		RCC_APB1_07_TIM13			DISABLE
#define 		RCC_APB1_06_TIM12			DISABLE
#define 		RCC_APB1_05_TIM7			DISABLE
#define 		RCC_APB1_04_TIM6			DISABLE
#define 		RCC_APB1_03_TIM5			DISABLE
#define 		RCC_APB1_02_TIM4			DISABLE
#define 		RCC_APB1_01_TIM3 			DISABLE
#define 		RCC_APB1_00_TIM2 			DISABLE


#endif 
