#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

/* Configure Pin Initial value : Options : 1- PUSH_PULL	2- OPENDRAIN  3- ALTERNATIVEFUNCTIONPUSH_PULL 4- ALTERNATIVEFUNCTIONOPENDRAIN    IF PIN is OUTPUT */
// 										   1- ANALOG 	2- FLOATING   3- PULLEDUP    													 IF PIN IS INPUT */


#define 		PORTA_PIN0_DIR  			PUSH_PULL
#define 		PORTA_PIN1_DIR  			PUSH_PULL
#define 		PORTA_PIN2_DIR  			PUSH_PULL
#define 		PORTA_PIN3_DIR  			PUSH_PULL
#define 		PORTA_PIN4_DIR  			PUSH_PULL
#define 		PORTA_PIN5_DIR  			PUSH_PULL
#define 		PORTA_PIN6_DIR  			PUSH_PULL
#define 		PORTA_PIN7_DIR  			PUSH_PULL
#define 		PORTA_PIN8_DIR  			PUSH_PULL
#define 		PORTA_PIN9_DIR  			PUSH_PULL
#define 		PORTA_PIN10_DIR  			PUSH_PULL
#define 		PORTA_PIN11_DIR  			PUSH_PULL
#define 		PORTA_PIN12_DIR  			PUSH_PULL
#define 		PORTA_PIN13_DIR  			PUSH_PULL
#define 		PORTA_PIN14_DIR  			PUSH_PULL
#define 		PORTA_PIN15_DIR  			PUSH_PULL

#define 		PORTB_PIN0_DIR  			PUSH_PULL
#define 		PORTB_PIN1_DIR  			PUSH_PULL
#define 		PORTB_PIN2_DIR  			PUSH_PULL
#define 		PORTB_PIN3_DIR  			PUSH_PULL
#define 		PORTB_PIN4_DIR  			PUSH_PULL
#define 		PORTB_PIN5_DIR  			PUSH_PULL
#define 		PORTB_PIN6_DIR  			PUSH_PULL
#define 		PORTB_PIN7_DIR  			PUSH_PULL
#define 		PORTB_PIN8_DIR  			PUSH_PULL
#define 		PORTB_PIN9_DIR  			PUSH_PULL
#define 		PORTB_PIN10_DIR  			PUSH_PULL
#define 		PORTB_PIN11_DIR  			PUSH_PULL
#define 		PORTB_PIN12_DIR  			PUSH_PULL
#define 		PORTB_PIN13_DIR  			PUSH_PULL
#define 		PORTB_PIN14_DIR  			PUSH_PULL
#define 		PORTB_PIN15_DIR  			PUSH_PULL

#define 		PORTC_PIN0_DIR  			PUSH_PULL
#define 		PORTC_PIN1_DIR  			PUSH_PULL
#define 		PORTC_PIN2_DIR  			PUSH_PULL

/* Configure Pin Direction : Options : 1- INPUT 2- OUTPUT10HZ 3- OUTPUT2HZ 4- OUTPUT50HZ */

#define 		PORTA_PIN0_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN1_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN2_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN3_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN4_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN5_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN6_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN7_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN8_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN9_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN10_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN11_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN12_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN13_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN14_INITVAL  		OUTPUT10HZ
#define 		PORTA_PIN15_INITVAL  		OUTPUT10HZ

#define 		PORTB_PIN0_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN1_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN2_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN3_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN4_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN5_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN6_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN7_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN8_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN9_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN10_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN11_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN12_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN13_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN14_INITVAL  		OUTPUT10HZ
#define 		PORTB_PIN15_INITVAL  		OUTPUT10HZ

#define 		PORTC_PIN0_INITVAL  		OUTPUT10HZ
#define 		PORTC_PIN1_INITVAL  		OUTPUT10HZ
#define 		PORTC_PIN2_INITVAL  		OUTPUT10HZ

/* Configure Pin Initial value : Options : 1- HIGH		2- LOW  				   	IF PIN is OUTPUT */
//										   1- FLOATING 	2- PULLEDUP   			 	IF PIN IS INPUT */

#define 		PORTA_PIN0_VAL  		HIGH
#define 		PORTA_PIN1_VAL  		HIGH
#define 		PORTA_PIN2_VAL  		HIGH
#define 		PORTA_PIN3_VAL  		HIGH
#define 		PORTA_PIN4_VAL  		HIGH
#define 		PORTA_PIN5_VAL  		HIGH
#define 		PORTA_PIN6_VAL  		HIGH
#define 		PORTA_PIN7_VAL  		HIGH
#define 		PORTA_PIN8_VAL  		HIGH
#define 		PORTA_PIN9_VAL  		HIGH
#define 		PORTA_PIN10_VAL  		HIGH
#define 		PORTA_PIN11_VAL  		HIGH
#define 		PORTA_PIN12_VAL  		HIGH
#define 		PORTA_PIN13_VAL  		HIGH
#define 		PORTA_PIN14_VAL  		HIGH
#define 		PORTA_PIN15_VAL  		HIGH

#define 		PORTB_PIN0_VAL  		LOW
#define 		PORTB_PIN1_VAL  		LOW
#define 		PORTB_PIN2_VAL  		LOW
#define 		PORTB_PIN3_VAL  		LOW
#define 		PORTB_PIN4_VAL  		LOW
#define 		PORTB_PIN5_VAL  		LOW
#define 		PORTB_PIN6_VAL  		LOW
#define 		PORTB_PIN7_VAL  		LOW
#define 		PORTB_PIN8_VAL  		LOW
#define 		PORTB_PIN9_VAL  		LOW
#define 		PORTB_PIN10_VAL  		LOW
#define 		PORTB_PIN11_VAL  		LOW
#define 		PORTB_PIN12_VAL  		LOW
#define 		PORTB_PIN13_VAL  		LOW
#define 		PORTB_PIN14_VAL  		LOW
#define 		PORTB_PIN15_VAL  		LOW

#define 		PORTC_PIN0_VAL  		LOW
#define 		PORTC_PIN1_VAL  		LOW
#define 		PORTC_PIN2_VAL  		LOW

#endif
